### ISSUE TITLE
nodejs Cannot find module 'optimist'

### ISSUE THREAD

**Issue by durandt** [mbloch/mapshaper#12]
Hi, 

I have some troubles running the latest version. 
I had no problem with a later fetch, that was from July 27th (commit 309baa8a2288aa3e86dbfbe14f61f120cb20c1d5). 

With the latest code I get:

```
user@host:~$ node /home/user/mapshaper/bin/mapshaper -i 1222 /home/user/shapes/MyShape.shp --dp -o /home/user/shapes/MyShapeSimplified.shp

module.js:340
    throw err;
          ^
Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/peroper/mapshaper/bin/mapshaper:22:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

I don't really have the time nor competence to look where the problem comes from, so I register this issue in case someone else has the problem with the latest code base. 

Regards,

Thibault D.

**Comment by TamaMcGlinn** [comment]
Thanks for making this issue. I don't even use mapshaper, but this popped up on google and makes clear that for node, you need to first go to the directory of the script before doing `npm install [package]`. That was unexpected, coming from other systems like pip.
