### ISSUE TITLE
new installation of mapshaper : TypeError: Cannot read property 'getFields' of undefined

### ISSUE THREAD

**Issue by geosacree** [mbloch/mapshaper#174]
That worked in previous version.

mapshaper 1.json  -merge-layers -o result.json 
/usr/local/lib/node_modules/mapshaper/mapshaper.js:1575
    throw err;
    ^

TypeError: Cannot read property 'getFields' of undefined
    at Object.MapShaper.checkLayersCanMerge (/usr/local/lib/node_modules/mapshaper/mapshaper.js:15003:17)
    at Object.api.mergeLayers (/usr/local/lib/node_modules/mapshaper/mapshaper.js:14949:13)
    at Object.api.runCommand (/usr/local/lib/node_modules/mapshaper/mapshaper.js:16612:26)
    at /usr/local/lib/node_modules/mapshaper/mapshaper.js:18583:9
    at Immediate.<anonymous> (/usr/local/lib/node_modules/mapshaper/mapshaper.js:18646:9)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by geosacree** [comment]
[1.json.zip](https://github.com/mbloch/mapshaper/files/790222/1.json.zip)

**Comment by mbloch** [comment]
Thanks for reporting this bug :) it affected datasets with no attribute data (like the single GeoJSON Polygon geometry in your example file). Fixed in v0.4.10.
