### ISSUE TITLE
Unable to use projection +init=EPSG:4326 (unable to read from 'init' file named EPSG)

### ISSUE THREAD

**Issue by simonepri** [mbloch/mapshaper#244]
## Problem
On Ubuntu I get this error:
```
[07:54:36] UserError: Unable to use projection +init=EPSG:4326 (unable to read from 'init' file named EPSG)
    at new UserError (./geo-maps/node_modules/mapshaper/mapshaper.js:1578:13)
    at internal.stop (./geo-maps/node_modules/mapshaper/mapshaper.js:1641:9)
    at stop (./geo-maps/node_modules/mapshaper/mapshaper.js:1574:17)
    at Object.internal.getProjection (./geo-maps/node_modules/mapshaper/mapshaper.js:13742:7)
    at Object.internal.getProjectionInfo (./geo-maps/node_modules/mapshaper/mapshaper.js:17105:27)
    at ./geo-maps/node_modules/mapshaper/mapshaper.js:18930:35
    at Array.forEach (<anonymous>)
    at ./geo-maps/node_modules/mapshaper/mapshaper.js:18922:19
    at Object.internal.initProjLibrary (./geo-maps/node_modules/mapshaper/mapshaper.js:13680:50)
    at Object.api.runCommand (./geo-maps/node_modules/mapshaper/mapshaper.js:18919:16)
```

## Workaround
change
```
+init=EPSG:4326
```
to
```
+init=epsg:4326
```

**Comment by mbloch** [comment]
This should be fixed in `v0.4.59`
