### ISSUE TITLE
Missing path data when using simplify on applyCommands

### ISSUE THREAD

**Issue by jessereitsma** [mbloch/mapshaper#254]
Hi,

I got the following error:
```
err { UserError: Missing path data
    at new UserError (/Users/jesse/Projects/Reclamefolder/postcode-to-geojson/node_modules/mapshaper/mapshaper.js:1578:13)
    at internal.stop (/Users/jesse/Projects/Reclamefolder/postcode-to-geojson/node_modules/mapshaper/mapshaper.js:1641:9)
    at stop (/Users/jesse/Projects/Reclamefolder/postcode-to-geojson/node_modules/mapshaper/mapshaper.js:1574:17)
    at Object.api.simplify (/Users/jesse/Projects/Reclamefolder/postcode-to-geojson/node_modules/mapshaper/mapshaper.js:18328:14)
    at Object.api.runCommand (/Users/jesse/Projects/Reclamefolder/postcode-to-geojson/node_modules/mapshaper/mapshaper.js:18988:11)
    at nextCommand (/Users/jesse/Projects/Reclamefolder/postcode-to-geojson/node_modules/mapshaper/mapshaper.js:21332:9)
    at Immediate._onImmediate (/Users/jesse/Projects/Reclamefolder/postcode-to-geojson/node_modules/mapshaper/mapshaper.js:21400:9)
    at runCallback (timers.js:774:11)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5) name: 'UserError' }
```

My code:

```
mapshaper.applyCommands(`-i test.geojson -simplify dp 6% -o `, input, (err, output) => {

});
```

Where `input` is an object containing `test.geojson` as property key which has a geoJSON stringified as value.

I previously ran this command as follows:
```
return childprocess.exec(`./node_modules/.bin/mapshaper -i ${filename} -simplify dp 6% -o force ${filename}`);
```

Where filename equals `test.geojson`

When I remove the `-simplify` option, it does work.
But when applying the `-simplify` flag, it crashes on aforementioned error

**Comment by mbloch** [comment]
Hi, could you email me a data file that triggers this error? It will help me to reproduce it.

**Comment by jessereitsma** [comment]
Will do, e-mail is on it's way! Thanks
