### ISSUE TITLE
Current local installation instructions doesn't work under docker

### ISSUE THREAD

**Issue by sylvainfilteau** [mbloch/mapshaper#310]
I tried creating a Docker container for mapshaper in order to not install node on my computer without success.

Here is the Dockerfile I've made:

```dockerfile
FROM node:11

ADD . /usr/src/app

WORKDIR /usr/src/app

RUN npm install

CMD bin/mapshaper
```

When running this, I get the following error message:

```stacktrace
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '../mapshaper'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/src/app/bin/mapshaper:3:17)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

**Comment by mbloch** [comment]
Hi,
I just published v0.4.103, which uses `require('../mapshaper.js')` instead of `require('../mapshaper')`. I'm not going to try to reproduce the error myself, so please let me know if this fixes the problem for you.
