### ISSUE TITLE
TypeError: Cannot read property 'size' of null

### ISSUE THREAD

**Issue by matkoniecz** [mbloch/mapshaper#316]
mapshaper -i test.geojson -lines fields=building -o out.geojson

test.geojson content:

```
{
"type": "FeatureCollection",
"features": [
{
  "type": "Feature",
  "id": "way/52004195",
  "geometry": {
    "type": "Polygon",
    "coordinates": [
      [
        [
          19.9275616,
          50.0560056
        ],
        [
          19.9274007,
          50.055978
        ],
        [
          19.9275616,
          50.0560056
        ]
      ]
    ]
  }
}
]
}
```

Stack trace:

```
/usr/local/lib/node_modules/mapshaper/mapshaper.js:1598
    throw err;
    ^

TypeError: Cannot read property 'size' of null
    at Object.internal.getArcClassifier (/usr/local/lib/node_modules/mapshaper/mapshaper.js:10914:16)
    at api.lines (/usr/local/lib/node_modules/mapshaper/mapshaper.js:18081:29)
    at /usr/local/lib/node_modules/mapshaper/mapshaper.js:21834:23
    at Array.reduce (<anonymous>)
    at Object.internal.applyCommand (/usr/local/lib/node_modules/mapshaper/mapshaper.js:21833:23)
    at Object.api.runCommand (/usr/local/lib/node_modules/mapshaper/mapshaper.js:21664:31)
    at nextCommand (/usr/local/lib/node_modules/mapshaper/mapshaper.js:24153:9)
    at Immediate._onImmediate (/usr/local/lib/node_modules/mapshaper/mapshaper.js:24221:9)
    at runCallback (timers.js:796:20)
    at tryOnImmediate (timers.js:752:5)
```

**Comment by mbloch** [comment]
The coordinates of this sample dataset describe a collapsed shape with area 0, which gets converted to a null shape on import. Many of mapshaper's commands currently will fail ungracefully when applied to layers with null geometry.

To improve mapshaper's handling of null geometry, I see a couple of approaches. One, the program could display an error message and stop execution. Or, mapshaper could detect the lack of valid geometry and print a warning instead of halting (in this example, the -lines command would trigger a warning).

I'm inclined to take the second approach, but I'm open to suggestions.
