### ISSUE TITLE
output > 2GB terminates with an error

### ISSUE THREAD

**Issue by TrantorM** [mbloch/mapshaper#358]
when mapshaper combines to large files (1.93 + 0.9 GB) as following:

```node  --max-old-space-size=32000 `which mapshaper` -i ./world/eurasia.geojson ./asia2/asia2_simp18_unslivered.geojson combine-files -merge-layers -o force ./world/eurasia.geojson precision=0.00001```

it terminates after a while with the following error:
```
/Users/Marcello/.npm-packages/lib/node_modules/mapshaper/mapshaper.js:1628
    throw err;
    ^

RangeError [ERR_INVALID_OPT_VALUE]: The value "2835025372" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:284:3)
    at Function.concat (buffer.js:463:25)
    at Object.GeoJSON.joinOutputBuffers (/Users/Marcello/.npm-packages/lib/node_modules/mapshaper/mapshaper.js:8949:17)
    at Object.GeoJSON.formatGeoJSON (/Users/Marcello/.npm-packages/lib/node_modules/mapshaper/mapshaper.js:8936:20)
    at Object.internal.exportDatasetAsGeoJSON (/Users/Marcello/.npm-packages/lib/node_modules/mapshaper/mapshaper.js:8924:20)
    at /Users/Marcello/.npm-packages/lib/node_modules/mapshaper/mapshaper.js:8790:25
    at Array.map (<anonymous>)
    at internal.exportGeoJSON (/Users/Marcello/.npm-packages/lib/node_modules/mapshaper/mapshaper.js:8785:22)
    at Object.internal.exportFileContent (/Users/Marcello/.npm-packages/lib/node_modules/mapshaper/mapshaper.js:17764:11)
    at /Users/Marcello/.npm-packages/lib/node_modules/mapshaper/mapshaper.js:17711:33
```

With `mapshaper-xl` the error is the same. Memory shouldn't be a problem, since it isn't going over 10GB in the monitor and I have 32GB installed. I guess the problem occurs in the end while writing out the result. Is there somewhere a limit of 2GB file size?

**Comment by mbloch** [comment]
The size of a Node Buffer is limited to 2GB on most systems (https://nodejs.org/api/buffer.html#buffer_buffer_constants_max_length)[reference]. 

Mapshaper accumulates GeoJSON output in a single buffer before writing it to disk. I believe that the size limitation could be removed by streaming the output to a file instead.

 I don't have time to work on this change right away, but it's worth considering.

Meanwhile, is there anything you can do to get the size of your files down a bit, like looping off a few digits of coordinate precision, or removing a few data data properties?

**Comment by TrantorM** [comment]
Streaming the output to a file sounds very interesting. How can I do that? I couldn't find any example. I tried with piping:
`node  --max-old-space-size=32000 `which mapshaper` -i ./world/eurasia.geojson ./asia2/asia2_simp18_unslivered.geojson combine-files -merge-layers -o format=geojson precision=0.00001 - | gzip > test.gz`
but it ended up in the same error.

Further reducing the file size is difficult, because I already simplified as much as possible. There are just 7 features with each 3 integer properties (id, elev_min, elev_max). The file serves as an input file for tippecanoe, therefore I can't go to an other format. Leave the two files splited would be an option, but the downside is: one can see the cutting edge when filling the polygons (there appears a thin white line on the display at the cutting edge).

**Comment by mbloch** [comment]
The switch to streaming output that I was talking about is not something that you, the end user, can do. Changes would have to be made to mapshaper's source code.

Doesn't tippecanoe accept Shapefile input as well as GeoJSON? How about saving your merged data to the Shapefile format?
