### ISSUE TITLE
[ERR_INVALID_OPT_VALUE] error

### ISSUE THREAD

**Issue by epilurzu** [mbloch/mapshaper#415]
I read the Issue [#358](https://github.com/mbloch/mapshaper/issues/358) and [#360](https://github.com/mbloch/mapshaper/issues/360) but I haven't solved my problem.

I have a shp file of 1.15GB, but running `mapshaper-xl 16gb myfile.shp -o format=geojson` I obtain the output:
```
Allocating 16 GB of heap memory
[o] RFC 7946 warning: non-WGS84 GeoJSON output. Tip: use "-proj wgs84" to convert.
RangeError [ERR_INVALID_OPT_VALUE]: The value "2835687348" is invalid for option "size"
    at Function.allocUnsafe (buffer.js:290:3)
    at Function.concat (buffer.js:472:23)
    at Object.GeoJSON.joinOutputBuffers (/mnt/c/Users/.../mapshaper.js:12627:19)
    at Object.GeoJSON.formatGeoJSON (/mnt/c/Users/.../mapshaper.js:12614:22)
    at exportDatasetAsGeoJSON (/mnt/c/Users/.../mapshaper.js:12602:22)
    at /mnt/c/Users/.../mapshaper.js:12469:18
    at Array.map (<anonymous>)
    at exportGeoJSON (/mnt/c/Users/.../mapshaper.js:12464:24)
    at exportGeoJSON2 (/mnt/c/Users/.../mapshaper.js:12430:12)
    at exportFileContent (/mnt/c/Users/.../mapshaper.js:14986:13)
```

With that size I should be able to convert my file, am I right? What am I missing?

BTW, can I ask you where I should put the `-proj wgs84` option in the command? I didn't figure that out.

**Comment by mbloch** [comment]
The error was thrown because your GeoJSON output is larger than the maximum size of a Node "Buffer" (2GB on most systems). To reduce output file size, you could try reducing the precision of the output coordinates. For 7-decimal precision, do this:
```
mapshaper-xl 16gb myfile.shp -o myfile.geojson precision=0.0000001
```

Mapshaper runs commands in sequence, so put `-proj wgs84` right before the output command `-o`: 
```
mapshaper-xl 16gb myfile.shp -proj wgs84 -o myfile.geojson precision=0.0000001
```

**Comment by epilurzu** [comment]
Thank you so much!
