### ISSUE TITLE
dissolve2 terminates with exception if dataset is empty

### ISSUE THREAD

**Issue by hyperknot** [mbloch/mapshaper#465]
If filter islands removes all the features in a dataset, `dissolve2` terminates with exception. 

Input:
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              18.9883553981781,
              47.45933912768112
            ],
            [
              18.98836612701416,
              47.4593318737723
            ],
            [
              18.98836612701416,
              47.459324619862485
            ],
            [
              18.98836076259613,
              47.459317365951705
            ],
            [
              18.9883553981781,
              47.45933912768112
            ]
          ]
        ]
      },
      "type": "Feature"
    }
  ]
}
```

command:
```
mapshaper in.geojson -filter-islands min-area=1km2 -dissolve2 
```

output:
```
[filter-islands] Removed 1 island
TypeError: Cannot read property 'size' of null
    at getArcPresenceTest (mapshaper/mapshaper.js:2926:38)
    at dissolvePolygonGroups2 (mapshaper/mapshaper.js:21938:21)
    at dissolvePolygonLayer2 (mapshaper/mapshaper.js:21890:19)
    at mapshaper/mapshaper.js:25238:14
    at Array.map (<anonymous>)
    at Object.cmd.dissolve2 (mapshaper/mapshaper.js:25237:19)
    at runCommand (mapshaper/mapshaper.js:30751:28)
    at nextCommand (mapshaper/mapshaper.js:31263:7)
    at Immediate._onImmediate (mapshaper/mapshaper.js:296:11)
    at processImmediate (internal/timers.js:458:21)
```

I believe the right solution would be to pass-through the geometry, like with `dissolve`.

**Comment by mbloch** [comment]
This is will be fixed in the next release
