### ISSUE TITLE
Unable to process large shapefile

### ISSUE THREAD

**Issue by hallahan** [mbloch/mapshaper#47]
I am trying to process a 1.2GB USA Census Block Group file. When trying to do the basic operation:

```
mapshaper -p 0.1 usa_census_block_groups.shp -f shapefile -o test.shp
```

I get the following error:

```
buffer.js:194
      this.parent = new SlowBuffer(this.length);
                    ^
RangeError: length > kMaxLength
    at new Buffer (buffer.js:194:21)
    at Object.fs.readFileSync (fs.js:302:14)
    at Object.Node.readFile (/usr/local/lib/node_modules/mapshaper/mapshaper.js:1299:20)
    at Object.MapShaper.readGeometryFile (/usr/local/lib/node_modules/mapshaper/mapshaper.js:9946:20)
    at Object.MapShaper.importFromFile (/usr/local/lib/node_modules/mapshaper/mapshaper.js:9934:27)
    at /usr/local/lib/node_modules/mapshaper/bin/mapshaper:43:28
    at Object.Utils.mapFilter (/usr/local/lib/node_modules/mapshaper/mapshaper.js:92:19)
    at Object.Utils.forEach (/usr/local/lib/node_modules/mapshaper/mapshaper.js:861:9)
    at procFiles (/usr/local/lib/node_modules/mapshaper/bin/mapshaper:37:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/mapshaper/bin/mapshaper:19:3)
```

**Comment by gingemonster** [comment]
I am still having a similar issue using

* node windows64 v0.12.5 
* mapshaper 0.2.27

I am trying to process a 1.072 GB file as follows:

mapshaper -i "C:\temp\adminlevel-8.shp" encoding=utf8 -simplify 5% keep-shapes -o "C:\temp\\adminlevel-8_5.shp" format=shapefile force

And I get this error in console:

C:\Users\Brian\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:1461
    throw err;
          ^
RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff byte
s
    at new Buffer (buffer.js:71:11)
    at Object.fs.readFileSync (fs.js:372:16)
    at Object.module.exports [as readFileSync] (C:\Users\Brian\AppData\Roaming\n
pm\node_modules\mapshaper\node_modules\rw\lib\rw\read-file-sync.js:6:15)
    at Object.cli.readFile (C:\Users\Brian\AppData\Roaming\npm\node_modules\maps
haper\mapshaper.js:14947:20)
    at Object.api.importFile (C:\Users\Brian\AppData\Roaming\npm\node_modules\ma
pshaper\mapshaper.js:10882:21)
    at Object.api.importFiles (C:\Users\Brian\AppData\Roaming\npm\node_modules\m
apshaper\mapshaper.js:10869:19)
    at Object.api.runCommand (C:\Users\Brian\AppData\Roaming\npm\node_modules\ma
pshaper\mapshaper.js:13394:21)
    at C:\Users\Brian\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:14
830:9
    at Immediate._onImmediate (C:\Users\Brian\AppData\Roaming\npm\node_modules\m
apshaper\mapshaper.js:14880:9)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by mbloch** [comment]
Thanks for reporting this :)  I just published version 0.2.28, which restores support for large .shp files.

**Comment by gingemonster** [comment]
great thanks Matthew ill try it out asap

**Comment by gingemonster** [comment]
It now doesnt show any kind of error but it also doesnt complete the simplification task. Im using this command

mapshaper -i "C:\temp\adminlevel-8.shp" encoding=utf8 -simplify 5% keep-shapes -o "C:\temp\adminlevel-8_5.shp" format=shapefile force

on a 1gb (approx) shp file

**Comment by gingemonster** [comment]
seems to be falling over in PathImporter where it creates the 64bit arrays:

Float64Array(bufSize)

I tried to see what error that was throwing but it didnt seem to work in try catch. My bufSize value is coming back from:

var bufSize = reservedPoints > 0 ? reservedPoints : 20000;

as 68614808

**Comment by mbloch** [comment]
That's probably enough info for me to debug the problem, I'll look into
this issue tonight after work. Thanks :)

**Comment by gingemonster** [comment]
Thank you much appreciated

**Comment by mbloch** [comment]
The other day, I tried to investigate this issue on Windows 8.1 and Node 0.12.6 (which I'm running on my mac laptop in Parallels). I found that mapshaper tended to silently quit while importing files larger than about 500MB -- no console messages or stack trace, just lights out.

On a hunch, I installed io.js (https://iojs.org/en/index.html), which is generally compatible with Node.js but includes many new contributions and also (I think) a more recent version of the v8 engine. I was able to process files > 1GB using io.js in Windows.

I still don't know the reason why node doesn't perform as well in Windows. If you don't want to install io.js, you can try simplifying your file interactively using the browser interface in Firefox.

Hope this is useful :)

**Comment by gingemonster** [comment]
even with iosjs in silently fails at 100% simplification ill try linux instead

**Comment by mbloch** [comment]
You may have better results with Linux. There was one gotcha  that I ran into when installing io.js on Windows, which you may have avoided. The .msi installer that I got from the io.js website worked fine, but I had to edit my PATH to put the path to the io.js install directory in front of the path to the node directory.

**Comment by anandbn** [comment]
`mapshaper anarasimhan$ bin/mapshaper ~/Desktop/zcta5.geo.json --filter-fields=GEOID`

Throws the below error:

```
/Users/.../dev/scratchpad/mapshaper/mapshaper.js:1575
    throw err;
          ^
RangeError: length > kMaxLength
    at new Buffer (buffer.js:194:21)
    at Object.fs.readFileSync (fs.js:309:16)
    at Object.cli.readFile (/Users/anarasimhan/dev/scratchpad/mapshaper/mapshaper.js:12057:60)
    at Object.api.importFile (/Users/anarasimhan/dev/scratchpad/mapshaper/mapshaper.js:13626:19)
    at Object.api.importFiles (/Users/anarasimhan/dev/scratchpad/mapshaper/mapshaper.js:13599:19)
    at Object.api.runCommand (/Users/anarasimhan/dev/scratchpad/mapshaper/mapshaper.js:16740:27)
    at /Users/anarasimhan/dev/scratchpad/mapshaper/mapshaper.js:18748:9
    at Object.<anonymous> (/Users/anarasimhan/dev/scratchpad/mapshaper/mapshaper.js:18811:9)
    at Object.immediate._onImmediate (timers.js:363:16)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

**Comment by b0ric** [comment]
Same story: trying to simplify 1.3Gb GeoJSON file with mapshaper 0.4.29 and got following error:

```
/usr/local/lib/node_modules/mapshaper/mapshaper.js:1585
    throw err;
    ^

Error: "toString()" failed
    at Buffer.toString (buffer.js:495:11)
    at StringDecoder.utf8Text [as text] (string_decoder.js:180:16)
    at StringDecoder.write (string_decoder.js:64:46)
    at StripBOMWrapper.write (/usr/local/lib/node_modules/mapshaper/node_modules/iconv-lite/lib/bom-handling.js:35:28)
    at Object.decode (/usr/local/lib/node_modules/mapshaper/node_modules/iconv-lite/lib/index.js:42:23)
    at Object.internal.decodeString (/usr/local/lib/node_modules/mapshaper/mapshaper.js:5725:19)
    at Object.cli.readFile (/usr/local/lib/node_modules/mapshaper/mapshaper.js:12457:24)
    at Object.api.importFile (/usr/local/lib/node_modules/mapshaper/mapshaper.js:14289:19)
    at Object.api.importFiles (/usr/local/lib/node_modules/mapshaper/mapshaper.js:14262:19)
    at Object.api.runCommand (/usr/local/lib/node_modules/mapshaper/mapshaper.js:17372:27)
```

**Comment by mbloch** [comment]
@b0ric and @anandbn,
Your comments belong in issue #129, this issue is about loading large Shapefiles, and has been closed.

**Comment by mbloch** [comment]
@b0ric, I just added support for large GeoJSON importing... you can read about it in issue #129.

**Comment by marcelogeo22** [comment]
Hello ! 

How are you ?

I am trying to run a topology analysis on my shapefile but I´m getting the following mesage back:

"RangeError: Maximum call stack size exceeded"

What can i do to solve this error?
