### ISSUE TITLE
Merging cvs with topojson, get **TypeError: Cannot read property 'getRecords' of null**

### ISSUE THREAD

**Issue by JuliaDawson** [mbloch/mapshaper#498]
Hi, I hope you can help me with this error: Likely I am doing something wrong.  Thank you so much for your product. I am using a Windows computer. Interestingly, I cannot load the csv file nor the json file here, I get an unsupported file type message/

mapshaper countries-110m-original.topojson -join CountryRegion_onlyTopo.csv keys=name,name -o countries-110m-plusRegion.topojson -v
0.5.60
[join] Joined data from 177 source records to 177 target records
[**TypeError: Cannot read property 'getRecords' of null**]()
    at getJoinByKey (C:\Users\julia\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:34541:28)
    at joinAttributesToFeatures (C:\Users\julia\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:34533:24)
    at cmd.join (C:\Users\julia\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:34500:14)
    at C:\Users\julia\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:37808:25
    at Array.reduce (<anonymous>)
    at applyCommandToEachLayer (C:\Users\julia\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:37807:25)
    at runCommand (C:\Users\julia\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:37592:9)
    at nextCommand (C:\Users\julia\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:38037:7)
    at Immediate._onImmediate (C:\Users\julia\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:298:11)
    at processImmediate (internal/timers.js:466:21)

**Comment by mbloch** [comment]
I think I see the problem. Most mapshaper commands get applied to one or more target layers. After importing a TopoJSON file, all the layers in the file become targets for the next command. Your input file contains two layers, "countries" and "land", so mapshaper tried to apply the join command to both of them.  The command succeeded on the first target (countries) but errored on the second target (land), because the land layer doesn't have any data properties.

The solution is to target specific layers using the `-target` command, like this:

```
mapshaper countries-110m-original.topojson -target countries -join CountryRegion_onlyTopo.csv keys=name,name -target countries,land -o countries-110m-plusRegion.topojson
```

I'll think about how to handle this particular error more gracefully (mapshaper should display a useful error message instead of a stack trace).

**Comment by mbloch** [comment]
I hope my above explanation made sense. I added an error message to help in this situation.
