### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by psociety** [mbloch/mapshaper#501]
Hi!

I'm trying to use this tool with a 1.2GB SHP file but i'm getting the following error:
```
D:\map_test>mapshaper gis_osm_roads_free_1.shp -o format=geojson spain.json
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <= 2147483647. Received 2349202044
    at Object.writeSync (fs.js:722:5)
    at Object.writeFileSync (fs.js:1530:26)
    at Object.module.exports [as writeFileSync] (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\node_modules\rw\lib\rw\write-file-sync.js:14:8)
    at Object.cli.writeFile (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:6381:10)
    at C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:6487:15
    at Array.forEach (<anonymous>)
    at _writeFiles (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:6475:15)
    at writeFiles (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:6454:12)
    at runCommand (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:37747:16)
    at nextCommand (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:38171:7) {
  code: 'ERR_OUT_OF_RANGE'
}
```

```
D:\map_test>mapshaper-xl gis_osm_roads_free_1.shp -o format=geojson spain.json
Allocating 8 GB of heap memory
RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be >= 0 && <= 2147483647. Received 2349202044
    at Object.writeSync (fs.js:722:5)
    at Object.writeFileSync (fs.js:1530:26)
    at Object.module.exports [as writeFileSync] (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\node_modules\rw\lib\rw\write-file-sync.js:14:8)
    at Object.cli.writeFile (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:6381:10)
    at C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:6487:15
    at Array.forEach (<anonymous>)
    at _writeFiles (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:6475:15)
    at writeFiles (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:6454:12)
    at runCommand (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:37747:16)
    at nextCommand (C:\Users\yo\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:38171:7) {
  code: 'ERR_OUT_OF_RANGE'
}
```

What i'm doing wrong?

**Comment by mbloch** [comment]
It looks like your output file is a bit larger than the maximum size of a buffer in Node.js (usually 2GB). I haven't done the work it would take to support outputting files this large.

You can reduce the size of GeoJSON files by rounding the coordinates to, say, 6 or 7 decimal places, which is still precise enough for most map making tasks. For example:

```
mapshaper-xl gis_osm_roads_free_1.shp -o format=geojson precision=0.000001 spain.json
```
