### ISSUE TITLE
Parsing of some shape files triggers "Shapefile contains an out-of-sequence record. Possible data corruption -- bailing." error

### ISSUE THREAD

**Issue by jaltin** [mbloch/mapshaper#519]
Hi,

We are seeing this error firing for some shape files when we try to parse them.

When we parse the shape files with other software it works ok (we tried QGIS, DotSpatial and https://maps.equatorstudios.com), but when we use mapshaper it fires the following error:

UserError: Shapefile contains an out-of-sequence record. Possible data corruption -- bailing.    at new UserError (C:\home\site\wwwroot\node_modules\mapshaper\mapshaper.js:1273:15)    at _stop (C:\home\site\wwwroot\node_modules\mapshaper\mapshaper.js:1184:11)    at stop (C:\home\site\wwwroot\node_modules\mapshaper\mapshaper.js:1210:11)    at readNextShape (C:\home\site\wwwroot\node_modules\mapshaper\mapshaper.js:21277:11)    at ShpReader.nextShape (C:\home\site\wwwroot\node_modules\mapshaper\mapshaper.js:21238:19)    at ShpReader.forEachShape (C:\home\site\wwwroot\node_modules\mapshaper\mapshaper.js:21229:24)    at importShp (C:\home\site\wwwroot\node_modules\mapshaper\mapshaper.js:21680:12)    at importShapefile (C:\home\site\wwwroot\node_modules\mapshaper\mapshaper.js:22795:19)    at importContent (C:\home\site\wwwroot\node_modules\mapshaper\mapshaper.js:22741:17)    at _importFile (C:\home\site\wwwroot\node_modules\mapshaper\mapshaper.js:22958:12)

We are trying to do the parsing via applyCommand in an Azure function and that's where we are getting the error.

If we try to parse the shapefile on https://mapshaper.org I also get the error.

Could it be a bug in Mapshaper or is the shape file faulty? Since other software can process the file, I hope there is a possible fix for this in mapshaper so that it can also process the layer.

I have attached a sample shapefile that triggers the error.

[data_corruption_error.zip](https://github.com/mbloch/mapshaper/files/7692360/data_corruption_error.zip)

Let me know if I can help further.

**Comment by ThomasG77** [comment]
Do not have an explanation but doing (considering you have installed GDAL) solve the issue magically

```
ogr2ogr -t_srs "EPSG:3006" out_check_proj.shp data_corruption_error.shp
zip out_check_proj_zip.zip out_check_proj.*
```

Then, test on Mapshaper GUI works whereas I had the same issue as you.

The more surprising is the fact that both original and modified files infos from `ogrinfo` are the same except the file name (see below)

```
ogrinfo -so data_corruption_error.shp data_corruption_error > data_corruption_error_meta.txt
ogrinfo -so out_check_proj.shp out_check_proj > out_check_proj_meta.txt
diff data_corruption_error_meta.txt out_check_proj_meta.txt
```

returns

```
1c1
< INFO: Open of `data_corruption_error.shp'
---
> INFO: Open of `out_check_proj.shp'
4c4
< Layer name: data_corruption_error
---
> Layer name: out_check_proj
6c6
<   DBF_DATE_LAST_UPDATE=2021-08-24
---
>   DBF_DATE_LAST_UPDATE=2021-12-10
```

**Comment by mbloch** [comment]
Thanks for reporting this -- I will investigate and try to find a way to handle these files. I noticed that `ogrinfo` prints an error as well (see below). If QGIS can import the file, it must not be an unrecoverable error.

output from running `ogrinfo data_corruption_error.shp `
```
INFO: Open of `data_corruption_error.shp'
      using driver `ESRI Shapefile' successful.
1: data_corruption_error (3D Measured Line String)
```

**Comment by ThomasG77** [comment]
> INFO: Open of `data_corruption_error.shp'
>
> using driver `ESRI Shapefile' successful.
> 1: data_corruption_error (3D Measured Line String)

This does not mean it's an error from GDAL perspective: it only means the layer name is `data_corruption_error` for `data_corruption_error.shp`.

Try `ogrinfo -so data_corruption_error.shp ogrinfo data_corruption_error`

Tested with GDAL 3.4

**Comment by mbloch** [comment]
I was misinterpreting the `ogrinfo` output -- thanks for pointing that out!

I figured out what was causing the errors. Each record in a .shp file has a "record number" field. According to the Shapefile spec, record numbers should be sequential and should start at 1. The erroring files have non-standard record numbers. The record number is not needed to read the data, and is a bit redundant, because the record number can also be inferred from the record's position in the .shx index file.

GDAL/OGR (and QGIS) apparently do not consider out-of-sequence record numbers to be a fatal error, which seems reasonable. Still, I think it's worth warning the user about this -- it could be a sign that the shapes in the Shapefile are associated with the wrong attribute data records, that the data has gotten scrambled.

So I've updated mapshaper to import these files (v0.5.79), and I'm printing a warning message. The warnings are a bit verbose -- I'll try to find a way to condense them. 

For example:
```
max_callstack_error $ mapshaper max_callstack_error.shp
[i] Warning: A feature has a different record number in .shx (1) and .shp (0).
[i] Warning: A feature has a different record number in .shx (2) and .shp (0).
[i] Warning: A feature has a different record number in .shx (3) and .shp (1).
[i] Warning: A feature has a different record number in .shx (4) and .shp (1).
[i] Warning: A feature has a different record number in .shx (5) and .shp (2).
[i] Warning: A feature has a different record number in .shx (6) and .shp (2).
[i] Warning: A feature has a different record number in .shx (7) and .shp (3).
[i] Warning: A feature has a different record number in .shx (8) and .shp (3).
[i] Warning: A feature has a different record number in .shx (9) and .shp (4).
[i] Warning: A feature has a different record number in .shx (10) and .shp (4).
[i] Warning: A feature has a different record number in .shx (11) and .shp (5).
[i] Warning: A feature has a different record number in .shx (12) and .shp (5).
[i] Warning: A feature has a different record number in .shx (13) and .shp (6).
[i] Warning: A feature has a different record number in .shx (14) and .shp (6).
[i] Warning: A feature has a different record number in .shx (15) and .shp (7).
[i] Warning: A feature has a different record number in .shx (16) and .shp (7).
```

**Comment by jaltin** [comment]
Hi @mbloch,

As mentioned in #518, I can confirm that the latest release 0.5.79 fixes this issue and then one mentioned in #519.

Thanks so much!
