### ISSUE TITLE
TypeError: s.trimEnd is not a function

### ISSUE THREAD

**Issue by eczajk1** [mbloch/mapshaper#520]
Getting this error at `mapshaper@0.5.80`:

```sh
mapshaper-xl ./my-shp.shp \ snap -simplify .05 keep-shapes \ -o format=shapefile /home/output/simplified.shp
TypeError: s.trimEnd is not a function
    at /usr/local/lib/node_modules/mapshaper/mapshaper.js:18035:15
    at Array.map (<anonymous>)
    at cleanArgv (/usr/local/lib/node_modules/mapshaper/mapshaper.js:18033:17)
    at CommandParser.parseArgv (/usr/local/lib/node_modules/mapshaper/mapshaper.js:18146:18)
    at parseCommands (/usr/local/lib/node_modules/mapshaper/mapshaper.js:36356:30)
    at _runCommands (/usr/local/lib/node_modules/mapshaper/mapshaper.js:39141:18)
    at Object.runCommands (/usr/local/lib/node_modules/mapshaper/mapshaper.js:39044:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/mapshaper/bin/mapshaper:5:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
```

**Comment by mbloch** [comment]
Could you try installing v0.5.81 and trying again? I switched from trimEnd() and trimStart() to custom trim functions.

It looks like String#trimEnd() was added in Node version 10... are you by any chance using an older version of Node?

**Comment by eczajk1** [comment]
Yes that worked. And yes, I was using an old Node version. :sweat_smile: 

Thanks - and thanks for this project. Happy Holidays.
