### ISSUE TITLE
Error when output GeoJson with dissolve option

### ISSUE THREAD

**Issue by wohenbushuang** [mbloch/mapshaper#523]
Windows 10 mapshaper 0.5.85

When I deal with a large (780MB zip, 1.05GB shp inside) https://osmdata.openstreetmap.de/download/land-polygons-complete-3857.zip

```sh
# shapefile, -dissolve, ok
mapshaper-xl ^
    -i ./tmp/land-polygons-complete-3857/land_polygons.shp ^
    -filter-fields ^
    -dissolve ^
    -o precision=0.000001 format=shapefile ./maps/earth-coastlines.shp ^
    -verbose
# geojson, no -dissolve, ok
mapshaper-xl ^
    -i ./tmp/land-polygons-complete-3857/land_polygons.shp ^
    -filter-fields ^
    -o precision=0.000001 format=geojson ./maps/earth-coastlines.geo.json ^
    -verbose
```
but
```sh
# geojson, -dissolve, fail
mapshaper-xl ^
    -i ./tmp/land-polygons-complete-3857/land_polygons.shp ^
    -filter-fields ^
    -dissolve ^
    -o precision=0.000001 format=geojson ./maps/earth-coastlines.geo.json ^
    -verbose
```
gives
```
Allocating 8 GB of heap memory
[i] Importing: ./tmp/land-polygons-complete-3857/land_polygons.shp
[i] - 13025ms
[filter-fields] - 412ms
[dissolve] Dissolved 709,263 features into 1 feature
[dissolve] - 409ms
[wkt] unhandled parameter: Auxiliary_Sphere_Type
[o] RFC 7946 warning: non-WGS84 GeoJSON output. Tip: use "-proj wgs84" to convert.
[o] - 49585ms
RangeError: Invalid string length
    at stringify (<anonymous>)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:12924:15
    at Array.reduce (<anonymous>)
    at exportLayerAsGeoJSON (C:\Users\admin\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:12906:41)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:13005:19
    at Array.reduce (<anonymous>)
    at exportDatasetAsGeoJSON (C:\Users\admin\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:13004:25)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:12880:18
    at Array.map (<anonymous>)
    at exportGeoJSON (C:\Users\admin\AppData\Roaming\npm\node_modules\mapshaper\mapshaper.js:12875:24)
```

**Comment by mbloch** [comment]
You're probably getting the "Invalid string length" error because you've got a single extremely long GeoJSON geometry. Mapshaper currently is unable to export single features that are larger than the maximum JS string length. That's around 500GB in a typical Node.js install (I think). You can try inserting an `-explode` command after your `-dissolve` command, to split your single MultiPolygon geometry into individual polygons.

**Comment by wohenbushuang** [comment]
Thanks for your replying. BTW my `node` version is 14.17.

The GeoJson format is not mandatory for me, just my first time choice, and I output shapefile now without failure. I've seen the discussion about streaming json such as the closed #129 , so at that time I thought it is no more a problem. Nevertheless, this issue's intention is the question: for the similar size json, why `-dissolve` fails (`dissolve` function is ok actually and done in `409ms` as the log shows) but ok without it (even with a larger output file size containing a lot of duplicate keys `coordinates`)? The shapefile output case shows the input shapefile has no problems for the whole mapshaper process, and the json output case without `-dissolve` case shows the large (at least for this size) json file output ability. Maybe the streaming json output part has some bugs, I thought?

The `-dissolve` switch is just because I refered other posts before and my post processing program just implement for MultiPolygon so far. I've tried `-dissolve multipart`, and nothing differed.

I indeed make a mistake that I used to think that `-proj` is used to illustrate the input file's projection, and the same name `.prj` file has include the projection infomation so I can omit it. ~~But for now, I wonder how can mapshaper recognize the projection if for GeoJson input files?~~

> If you want lat,long coordinates (which is standard for the GeoJSON format)

Oh I see

**Comment by tobwen** [comment]
I have similar issues with `EPSG:3857`, but here the warning occurs directly after reading:

```
Allocating 40 GB of heap memory
[i] Importing: test_3857.shp
[i] - 39003ms
[wkt] unhandled parameter: Auxiliary_Sphere_Type
[dissolve2] Dissolved 3,441,487 features into 6 features
...
```

I think I'll create an issue on its own for this.
