### ISSUE TITLE
Error when export kmz file to geojson

### ISSUE THREAD

**Issue by terrencesiow** [mbloch/mapshaper#577]
When i try to export kmz file to geojson, the CLI will show error. Any possible solution? Thank you.

Command : 
**mapshaper file.kmz -o file.geojson format=geojson target=1**

Error:
**/usr/lib/node_modules/mapshaper/node_modules/@tmcw/togeojson/dist/togeojson.cjs:18
    node?.normalize();
         ^
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at importKML (/usr/lib/node_modules/mapshaper/mapshaper.js:27371:21)
    at importContent (/usr/lib/node_modules/mapshaper/mapshaper.js:27417:17)
    at _importFile (/usr/lib/node_modules/mapshaper/mapshaper.js:27772:12)**

Version:
**0.6.25**

**Comment by mbloch** [comment]
Hi! I was unable to reproduce this error. Is it possible that you're running an older version of Node? What do you see when you run `node -v` ?

**Comment by terrencesiow** [comment]
Hi @mbloch , my node is v10. After the node updated to latest version, the issue been solved.
