### ISSUE TITLE
Javascript error related to polygon editing causes GUI to crash

### ISSUE THREAD

**Issue by charliesmart** [mbloch/mapshaper#632]
Started seeing this while using the new polygon editing tools. It caused the whole GUI to freeze/get stuck in an error loop.

<img width="353" alt="image" src="https://github.com/mbloch/mapshaper/assets/16366261/0b9619e8-6740-4fae-b260-0da04fbb434d">

This appears in the javascript console:

```
mapshaper-gui.js:2432 Uncaught Error: #getArcId() out-of-range arc id: 734
    at error (mapshaper-gui.js:2432:13)
    at error (mapshaper.js:1247:12)
    at ArcCollection.getArcIter (mapshaper.js:5873:9)
    at ShapeIter.nextArc (mapshaper.js:5418:30)
    at ShapeIter.reset (mapshaper.js:5426:10)
    at ShapeIter.init (mapshaper.js:5411:10)
    at ArcCollection.getShapeIter (mapshaper.js:5879:34)
    at getPointToPathInfo (mapshaper.js:2429:21)
    at mapshaper.js:2470:22
    at Array.reduce (<anonymous>)
```

**Comment by mbloch** [comment]
This error is fixed, thanks!
