### ISSUE TITLE
Can I use mapshaper in a React vite app?

### ISSUE THREAD

**Issue by skudev** [mbloch/mapshaper#665]
Hi,

when I try to use mapshaper in my React vite app, I get this error message

__vite-browser-external:crypto:3 Uncaught Error: Module "crypto" has been externalized for browser compatibility. Cannot access "crypto.randomFillSync" in client code.  See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
    at Object.get (__vite-browser-external:crypto:3:11)
    at <stdin> (zipcrypto.js?v=93aa1cb2:10:13)
    at __require (zipcrypto.js?v=93aa1cb2:3:50)
    at zipcrypto.js?v=93aa1cb2:126:16

Is mapshaper meant to be used  in a React vite app? I am migrating a React project which used mapshaper-es with some webpack configuration. But as mapshaper-es has beeen deprecated I would love to migragte to mapshaper if possible.

**Comment by skudev** [comment]
I have tried to polyfill crypto and other node modules but still get this error: 
Uncaught Error: Dynamic require of "iconv-lite" is not supported
    at chunk-HG6TCYAD.js?v=08f0e83c:19:9
    at mapshaper.js:3742:7
    at node_modules/mapshaper/mapshaper.js (mapshaper.js:46704:4)
    at __require2 (chunk-HG6TCYAD.js?v=08f0e83c:25:50)
    at mapshaper.js:46704:4

Would you have the possibility to provide a browser build of mapshaper?

**Comment by skudev** [comment]
The project that I am migrating is using some of you  geoprocessing commands like 
  erase,
  simplify,
  dissolve2,
  clean,
  proj,
  explode,
  exportShpFromGeojson,
  exportGeojsonFromShp

**Comment by mbloch** [comment]
I'm not a React user, and I'm only supporting mapshaper as an end-user application, so there's not much I can do to help with this. The first error you saw may not be related to mapshaper at all -- mapshaper doesn't use `zipcrypto.js`. As for the second problem (dynamic require of `iconv-lite`), mapshaper puts most of its Node library dependencies in an external file, https://mapshaper.org/modules.js, which which is generated using browserify. You may need to come up with a different build process if you want to use mapshaper in a React app.
